config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # see all tasks
  get 'tasks', to: 'tasks#index'

  # add a task
  get 'tasks/new', to: 'tasks#new', as: :new
  post 'tasks', to: 'tasks#create', as: :create

  # show info about one task
  get 'tasks/:id', to: 'tasks#show', as: :show

  # edit a task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  # update a task
  patch 'tasks', to: 'tasks#update', as: :update

  # delete/destroy a task
  get 'destroy', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to show_path(@task)
    else
      render :new
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to show_path(@task)
    else
      render :edit
    end
  end

  def destroy
    @task = Task.destroy
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>edit:</h1>

<%= form_for @task, url: update_path, method: :patch do |f| %>
  <%= f.label :title  %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>


<!-- <input type="checkbox" name="vehicle1" value="Bike"> -->

app/views/tasks/index.html.erb
<h1>My Tasks:</h1>

<% @tasks.each do |task| %>
<h3><%= link_to task.title, show_path(task) %></h3>
<% end %>

<%= link_to "+ Add a task", new_path %>
<!-- <input type="checkbox" name="vehicle1" value="Bike"> -->

app/views/tasks/new.html.erb
<h1>My Tasks:</h1>

<%= form_for(@task) do |f| %>
<%= f.label :title  %>
<%= f.text_field :title %>
<%= f.submit %>
<% end %>


<!-- <input type="checkbox" name="vehicle1" value="Bike"> -->

app/views/tasks/show.html.erb
<h1>My Tasks:</h1>

<h3><%= @task.title %></h3>

<h3><%= link_to @task.title, show_path(@task) %></h3>

<h3><%= link_to "edit me", edit_path(@task) %></h3>